name: build-reproducible

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install TBD
      run: git clone https://github.com/reproducible-tidb/TBD.git ../TBD
    - name: Run jobs
      run: source ../TBD/TBD.sh tidb.TBD
      env:
        CI_NAME: githubaction
    - name: Move result json files
      run: |
        sha256sum=`sha256sum /publish/$pkgname-$pkgver-$pkgrel.tar | cut -d ' ' -f1`
        echo "{\"version\":\"$pkgver\",\"sha256\":\"$sha256sum\",\"timestamp\":\""`date +%s`"\"}" > /publish/$pkgname-$pkgver-$pkgrel.json
        mkdir results && mv ./*.json results/
    - name: Publish results
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: results-githubaction
        folder: results
